services:
  - type: web
    name: flask-app
    runtime: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: /opt/render/project/.render/python/bin/gunicorn app:app
    python:
      version: "3.9.16"